version: "3.8"

services:
  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/backend/envs/.env.db.dev

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/backend:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    env_file:
      - ./services/backend/envs/.env.dev
    depends_on:
      - db
      - redis
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
